### ISSUE TITLE
App Doesn't Show Most Recent Dat

### ISSUE THREAD

**Issue by Freeport2** [billdonner/qanda#1]
It looks like qanda is always using the same data file.  

No matter which setting I choose using the settings button on the app, I always get the same results.

The code says:

enum GameDataSource : Int {
  
  case localFull // keep first for easiest testing
  case gameDataSource1
  case gameDataSource2
  case gameDataSource3

These values appear incorrect
let PRIMARY_REMOTE = "https://billdonner.com/fs/gd/readyforios01.json"
let SECONDARY_REMOTE = "https://billdonner.com/fs/gd/readyforios02.json"
let TERTIARY_REMOTE = "https://billdonner.com/fs/gd/readyforios03.json"

The only json file I could find in the gd directory that has the first question that comes up in the app is validated-10k-pumper-output.json, so my suspicion is that local full is set to validated-10k-pumper-output somewhere but I couldn't figure out where.

**Comment by billdonner** [comment]
Those are the 3 places where the files should be, using FileZilla to get there.
It doesn't matter what's already there. Just put whatever you want in there.

It doesn't really matter what Prepper calls it, as long as it gets up there with one of those 3 names.

In the qanda app use the Settings to switch to whichever file you want and then go back to the front topics list, then re-run the whole thing and you should see what you intended.

**Comment by Freeport2** [comment]
We need to talk about this later.
